export const CONTACT_CREATE = "CREATE_CONTACT"
export const CONTACT_DELETE = "CONTACT_DELETE"
export const CONTACT_FETCH = "CONTACT_FETCH"

export const UPDATE_BOOK_ID = "UPDATE_BOOK_ID"
export const UPDATE_USER_ID = "UPDATE_USER_ID"
export const UPDATE_NAME = "UPDATE_NAME"
export const UPDATE_PHONE_NUMBER = "UPDATE_PHONE_NUMBER"